CREATE DATABASE AdoNETAppDB
USE AdoNETAppDB

CREATE TABLE Countries (
	Id INT PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(50) NOT NULL UNIQUE,
	Area DECIMAL(10, 2) NOT NULL 
)

CREATE TABLE Cities (
	Id INT PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(50) NOT NULL,
	Area DECIMAL(10, 2) NOT NULL,
	CountryId INT,
	FOREIGN KEY(CountryId) REFERENCES Countries(Id)
)

SELECT * FROM Countries
SELECT * FROM Cities


